### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by mocram** [picons/picons-source#199]
@charlesduco

Any idea how to get the line endings issue resolved? I can always do a dirty workaround on the server if all else fails....

**Comment by mocram** [comment]
I've worked around the issue, so at least all the LF drama will not stop the builds anymore.

**Comment by charlesduco** [comment]
I'm not 100% sure but I think Github ignores the .gitattributes file.

So if a file with crlf endings is uploaded through the Github web interface, we get crlf endings in the repository.

I can't find an idiot-proof solution for this problem yet. I think Github should fix their upload- and pull request functions and support the .gitattribute settings.

For now, we should inspect every pull request very carefully and check if line endings are LF.

**Comment by mcfly822** [comment]
So is it allowed now to make PRs through website?

**Comment by mocram** [comment]
So my last commit 5697c32d70c3ce7e2241aea921d9f98b9326324f should solve this once and for all. I hope. :-)

**Comment by mocram** [comment]
This evening I'm going to make some changes to streamline and fix this even more....my last commit is still not ideal.

**Comment by mocram** [comment]
Should be good to go now, if I broke something... I'll know tomorrow.

**Comment by mocram** [comment]
https://github.com/picons/picons-source/pull/201#issuecomment-346885682
